#geneSet: ['Signature_overlap_DASLarray_genes']
geneSet: ['Signature_overlap_DASLarray_genes', "ClinicalData", "LMC_150_genes", "Gerami_genes"]
#classifierName: ['rf', 'lda', 'knn', 'svmRadial', 'svmLinear', 'bayesglm', 'plr', 'glmnet']
classifierName: ['rf', 'lda', 'knn', 'svmRadial', 'svmLinear', 'bayesglm', 'glmnet']
#classifierName: ['lda']
seed: ['3']
applyPCA: ['FALSE']
#cvMethod: ['repeatedcv', 'boot']
cvMethod: ['boot']
